# Generated by Django 6.0.1 on 2026-02-15 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('type', models.CharField(default='unranked', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('duration', models.FloatField(blank=True)),
                ('problem', models.URLField(default='https://www.meme-arsenal.com/memes/bc792386d4bf2ad344989e5ecbb9206f.jpg')),
                ('spectators', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spectators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Battle',
                'verbose_name_plural': 'Battles',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='spectator', max_length=20)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='battles.battle')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='player_1',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='battles.participant'),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_2',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='battles.participant'),
        ),
    ]
