# Generated by Django 6.0.1 on 2026-02-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='player',
            new_name='user',
        ),
    ]
