# Generated by Django 6.0.1 on 2026-02-15 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_rename_player_participant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='spectators',
        ),
        migrations.AddField(
            model_name='battle',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Live'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('1v1', 'Duel')], default='1v1', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battles.battle'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('player', 'Player'), ('spectator', 'Spectator')], default='player', max_length=20),
        ),
    ]
