# Generated by Django 6.0.1 on 2026-02-15 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_remove_battle_player_1_remove_battle_player_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='invite_code',
            field=models.CharField(blank=True, default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('spectator', 'Spectator')], default='player', max_length=20),
        ),
    ]
