# Generated by Django 6.0.1 on 2026-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_battle_created_at_battle_invite_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
