# Generated by Django 6.0.1 on 2026-03-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_battle_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='problem',
            new_name='task',
        ),
    ]
