# Generated by Django 6.0.1 on 2026-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_rename_problem_battle_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='task',
            field=models.IntegerField(),
        ),
    ]
