# Generated by Django 6.0.1 on 2026-04-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0011_alter_battle_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
