# Generated by Django 6.0.1 on 2026-04-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0012_battle_max_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='max_members',
            field=models.IntegerField(),
        ),
    ]
