# Generated by Django 6.0.1 on 2026-04-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0014_battle_spectator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='max_members',
            new_name='max_participants',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='spectator',
        ),
    ]
