# Generated by Django 6.0.1 on 2026-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0015_rename_max_members_battle_max_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='type',
            field=models.CharField(choices=[('1v1', 'Duel'), ('group', 'Group')], default='1v1', max_length=20),
        ),
    ]
