# Generated by Django 6.0.1 on 2026-02-15 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=20)),
                ('code', models.TextField(max_length=65535)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='battles.battle')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=20)),
                ('execution_time', models.DurationField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='execution', to='submissions.submission')),
            ],
        ),
    ]
