# Generated by Django 6.0.1 on 2026-02-15 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_remove_battle_player_1_remove_battle_player_2_and_more'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='battles.participant'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='battles.battle'),
        ),
    ]
